### ISSUE TITLE
search API for distros should use `/` as a separator

### ISSUE THREAD

**Issue by alfredodeza** [ceph/shaman#47]
Since we want to allow both codename and version for search, this would cause issues when parsing:

    distros=ubuntu.14.04,ubuntu.16.08

The parsing code could just split on the first `.` but using a `/` would make it a bit more readable (less dots, and only when needed on versions):

    distros=ubuntu/14.04,ubuntu/16.08

**Comment by andrewschoen** [comment]
I'm fine with using ``/`` as a separator here.

**Comment by alfredodeza** [comment]
Fixed with PR #48
