### ISSUE TITLE
repo status should consume new key: `state`

### ISSUE THREAD

**Issue by alfredodeza** [ceph/shaman#5]
Because the current attributes in the model object for repositories includes:

* is_updating
* is_queued
* needs_update

But those are meant to help in controlling the flow of creating/managing repositories. Chacra could add more granular callbacks (for example: 'ready') and looking at keys to determine that would make it complicated to consume.

**Comment by andrewschoen** [comment]
https://github.com/ceph/shaman/pull/9 allows for updating of a field called ``status`` to use for this purpose. I'm going to close this, but if you feel strongly we can rename to ``state``.

**Comment by alfredodeza** [comment]
`"status"` sounds better
