### ISSUE TITLE
drop "arch" parameter for "latest" repos?

### ISSUE THREAD

**Issue by ktdreyer** [ceph/shaman#89]
This URL fails with an HTTP 504 error:
https://shaman.ceph.com/api/repos/ceph-ansible/master/latest/centos/7/repo

Appending `?arch=noarch` makes it work.

It's not totally clear to me why I have to append this to the URL just because it has noarch packages?

For context, I have a Shaman client that does something like this for a bunch of packages to download all the Yum repo definitions:

```python
URL = 'https://shaman.ceph.com/api/repos/%(pkg)s/%(branch)s/latest/centos/7/repo'
repo_url = URL % {'pkg': pkg, 'branch': branch}
log.info('downloading %s' % repo_url)
r = requests.get(repo_url)
```

... so `pkg = 'ceph'` works there, but `pkg = 'ceph-ansible'` does not.

How can I make them work with the same basic "URL"?

**Comment by andrewschoen** [comment]
I think this is a bug in shaman. What it does now is if ``?arch`` isn't specified it defaults to ``x86_64`` which doesn't work for all repos. I think what it should instead do is if ``x86_64`` isn't available it should ignore architecture and retrieve the latest repo built for any arch. Would that solution work for your use case here?

If users wanted to ensure they get a consistent architecture they could still use the ``?arch`` flag to do that.

**Comment by ktdreyer** [comment]
I see, yes, that would work!

**Comment by andrewschoen** [comment]
The fix for this has been deployed:

```
$ curl -L https://shaman.ceph.com/api/repos/ceph-installer/master/latest/centos/7/repo/
[ceph-installer]
name=ceph-installer packages for \$basearch
baseurl=https://1.chacra.ceph.com/r/ceph-installer/master/19ec4f5289402bcb4fd6ef269edf39f42ee8c0cf/centos/7/flavors/default/\$basearch
enabled=1
gpgcheck=0
type=rpm-md

[ceph-installer-noarch]
name=ceph-installer noarch packages
baseurl=https://1.chacra.ceph.com/r/ceph-installer/master/19ec4f5289402bcb4fd6ef269edf39f42ee8c0cf/centos/7/flavors/default/noarch
enabled=1
gpgcheck=0
type=rpm-md

[ceph-installer-source]
name=ceph-installer source packages
baseurl=https://1.chacra.ceph.com/r/ceph-installer/master/19ec4f5289402bcb4fd6ef269edf39f42ee8c0cf/centos/7/flavors/default/SRPMS
enabled=1
gpgcheck=0
type=rpm-md
```
