### ISSUE TITLE
show "flavor" column in repos UI

### ISSUE THREAD

**Issue by ktdreyer** [ceph/shaman#96]
I could not figure out why Teuthology would not let me schedule a suite against my Shaman packages.

Teuthology was saying that the [Shaman search API URL](https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros=ubuntu/14.04/x86_64&sha1=5f5a58888668f0b81b2759a7298c275b032f62ee) returned no builds for my distro, so I looked at the [repo UI](https://shaman.ceph.com/repos/ceph/jewel-integration-ktdreyer/5f5a58888668f0b81b2759a7298c275b032f62ee/) to confirm that there were "trusty" builds there.

As @dmick pointed out, the build there was the "notcmalloc" flavor, not the "default" flavor. It would be great to make this explicit in the Shaman UI with a "flavor" column in the main table.

**Comment by alfredodeza** [comment]
Already being tracked at http://tracker.ceph.com/issues/17933
